### ISSUE TITLE
ClassStructure: Improper string trim

### ISSUE THREAD

**Issue by ariddl** [ThomasAndrasek/The-Obfuscatorinator#33]
**Describe the bug**
Strings are immutable so the line
`implementedClass.trim()` inside `ClassStructure.java`
on its own does not change anything. Unsure of exactly what implications this has for the rest of the program.

**To Reproduce**
1. Write a simple Java program that includes a class that implements any interface.
2. Include trailing spaces before/after the interface names being implemented.
3. Run the obfuscator on your program and verify the obfuscated output.

**Expected behavior**
The class names should be trimmed to remove any spaces.

**Comment by ThomasAndrasek** [comment]
This issue has been resolved in the most recent pull request. Please pull update from the main branch for the fix!
